version: '3.8'
services:
    childs:
        container_name: childs
        build:
            context: childs
            dockerfile: dockerfile
        image: childs:latest
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
    houses:
        container_name: houses
        build:
            context: houses
            dockerfile: dockerfile
        image: houses:latest
        ports:
            - 8081:8080
        networks:
            - spring-cloud-network
    parentsummary:
        container_name: parentsummary
        build:
            context: parentsummary
            dockerfile: dockerfile
        image: parentsummary:latest
        ports:
            - 8082:8080
        networks:
            - spring-cloud-network
    parentsummaryjob:
        container_name: parentsummaryjob
        build:
            context: parentsummaryjob
            dockerfile: dockerfile
        image: parentsummaryjob:latest
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge
