version: '3.8'
services:
    childs:
        build:
            context: childs
            dockerfile: dockerfile
        image: childs:latest
        ports:
            - 8080-8090:8080
        networks:
            - spring-cloud-network
    houses:
        build:
            context: houses
            dockerfile: dockerfile
        image: houses:latest
        ports:
            - 8091-8100:8080
        networks:
            - spring-cloud-network
    parentsummary:
        build:
            context: parentsummary
            dockerfile: dockerfile
        image: parentsummary:latest
        ports:
            - 8101-8110:8080
        networks:
            - spring-cloud-network
    parentsummaryjob:
        build:
            context: parentsummaryjob
            dockerfile: dockerfile
        image: parentsummaryjob:latest
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge
